security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User:
            algorithm: 'bcrypt'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_USER: [ ]
        ROLE_ADMIN: [ ROLE_USER ]
        ROLE_BANNED: [ ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            logout:
                path: logout
                target: login
                invalidate_session: false
    access_control:
     - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
